CREATE OR REPLACE FUNCTION QUEUE_TABLE_INCREMENT(TABLE_ID UUID)
RETURNS TIMESTAMP
LANGUAGE PLPGSQL
AS 
$$
DECLARE 
	INCREMENT_DATETIME TIMESTAMP;
BEGIN
	SELECT COALESCE(MAX(QTI.INCREMENT_DATETIME),CAST('1900-01-01 00:00:00' AS TIMESTAMP))
	INTO INCREMENT_DATETIME
 	FROM META.QUEUE_TABLE_INCREMENT QTI
	WHERE QTI.QUEUE_TABLE_ID=TABLE_ID;
	
	RETURN INCREMENT_DATETIME;
END;
$$;


CREATE OR REPLACE FUNCTION MAX_QUEUE_TABLE_INCREMENT(TABLE_ID UUID)
RETURNS TIMESTAMP
LANGUAGE PLPGSQL
AS 
$$
DECLARE 
	MAX_INCREMENT_DATETIME TIMESTAMP;
BEGIN 
	EXECUTE 'SELECT MAX(src.INCREMENT_DATETIME) FROM STG."'||TABLE_ID||'" AS src'
	INTO MAX_INCREMENT_DATETIME;
	
	RETURN MAX_INCREMENT_DATETIME;
END;
$$;


CREATE OR REPLACE PROCEDURE UPDATE_QUEUE_TABLE_INCREMENT(TABLE_ID UUID)
LANGUAGE PLPGSQL
AS 
$$
DECLARE
	INCR_DTTM TIMESTAMP; /*максимальное время из таблицы STG*/
	PREV_INCR_DTTM TIMESTAMP; /*текущее время в META.QUEUE_TABLE_INCREMENT*/
BEGIN
	SELECT *
	INTO INCR_DTTM 
	FROM MAX_QUEUE_TABLE_INCREMENT(TABLE_ID);

	SELECT *
	INTO PREV_INCR_DTTM 
	FROM QUEUE_TABLE_INCREMENT(TABLE_ID);

	DELETE FROM META.QUEUE_TABLE_INCREMENT WHERE QUEUE_TABLE_ID=TABLE_ID;

	INSERT INTO META.QUEUE_TABLE_INCREMENT (QUEUE_TABLE_ID,INCREMENT_DATETIME)
	VALUES 
	(TABLE_ID, COALESCE(INCR_DTTM,PREV_INCR_DTTM));
END;
$$;